// configure EN settings for asciidoc
include::_config.adoc[]

= Requirements for CalendarMail

This document describes the requirements of <<index.adoc#,project CalendarMail>>.

[[section-goals]]
== Goals

The intention of this project is to solve the following goals:

* Fetch calendar information from different CalDAV locations
* Filter events for a given period
* Regularly send email reminders containing a summary of the following events


[[section-domain-model]]
== Domain Model

[glossary]
Remote Calendar::
A calendar in iCal format on a server, available via CalDAV protocol.
Reminder::
A scheduled job to be triggered regularly to filter calendar events and to send a email summary.
Email Server::
Email Server configuration to be used to send reminder emails.
User::
A person to invoke the program from a commandline.
Cron job::
A Unix cron job to execute a program in a repeated manner.
Scheduler::
A program part that triggers jobs to be executed at a time when it is configured.


[[section-usecase-overview]]
== Use Case Overview

For the software the following use cases have been identified:

.Use case overview
[plantuml, use_cases, png]
--
left to right direction
actor user
actor "cron job" as cron
rectangle CalendarMail {
 (single execution) as (single)
 (start cron) as (start)
 (read configuration) as (config)
 (scheduling)
 (send reminder) as (remind)
 (fetch remote calendar) as (fetch)
 (filter calendar events) as (filter)
 (send reminder email) as (email)

 user --> (encrypt)
 user --> (decrypt)
 user --> (start)
 cron --> (single)
 (start) ..> (scheduling) : <<include>>
 (single) ..> (scheduling) : <<include>>
 actor scheduler
 scheduler -up-> (scheduling)
 (config) ..> (scheduling) : <<extends>>
 (remind) .left.> (scheduling) : <<extends>>
 (remind) ..> (filter) : <<include>>
 (filter) .up.> (fetch) : <<include>>
 (remind) ..> (email) : <<include>>
}
--


[[section-detailed-usecases]]
== Detailed use cases

The identified use cases will be described below.
The https://www.sophist.de/fileadmin/SOPHIST/UML/uml2-4_linknummern/12-1_Schablone_fuer_%20Use-Case-Beschreibung.pdf[use case template of the SOPHIST group] will be used here.

=== Encrypt/decrypt

[[usecase-encrypt-decrypt]]
.UseCase Encrypt/Decrypt
[cols=">.^1s,<10"]
|====
|Goal | Encrypt / Decrypt a password for usage in configuration
|Actors | user
|Trigger | The user provides a password to be encrypted/decrypted on the commandline
|Steps | in <<steps-encrypt-decrypt, diagram>>
|====

[[steps-encrypt-decrypt]]
.Encryption/Decryption of a password
[plantuml, encryption-case, png]
--
start
:user executes program with string to be encrypted;
if (password given?) then (no)
    :promt for input of password;
endif
:encrypt string with given password;
:print encrypted string;
stop
--

=== Read configuration

[[usecase-read-config]]
.UseCase Encrypt/Decrypt
[cols=">.^1s,<10"]
|====
|Goal | A configuration file has to be interpreted
|Actors | system
|Trigger | At system start a configuration file is provided to be used
|Steps | in <<steps-read-config, diagram>>
|====

[[steps-read-config]]
.Reading configuration file
[plantuml, configuration-case, png]
--
start
if (external configuration file given?) then (yes)
    :read file with given name;
else (no)
    :read default configuration;
endif
:parse configuration;
if (fatal error?) then (yes)
    :print error message;
    :exit;
    stop
elseif (acceptable error?) then (yes)
    :print warning message;
else (no error)
endif
if (configuration contains encrypted passwords?) then (yes)
    if (encryption password provided at command line?) then (yes)
    else (no)
        :prompt for input of encryption password;
    endif
    :decrypt configuration passwords;
endif
:continue operation;
stop
--
